### ISSUE TITLE
[Cohort #5] | What is the recommendation with monthly updates/versions of Hummingbot?

### ISSUE THREAD

**Issue by thenkinet** [hummingbot/hummingbot-botcamp#40]
### Question

Please explain the recommendation with monthly updates. Do we need to re-clone the repository when we use the source, is it automated with Docker. Thank you!

**Comment by fengtality** [comment]
I recommend upgrading to the latest release as we are shipping a lot of new features each month now.

If installed from source: 

```
git pull origin [branch name]
./compile. # re-compile
```

If installed from Docker
```
docker compose up --force-recreate --build -d
```

**Comment by thenkinet** [comment]
Did it but the client shows version: dev-1.18.0 is that right? Shouldn't it be version 1.17.0 instead ??
