### ISSUE TITLE
[Cohort #5] | Theoretical papers and/or collaborations with CFEM

### ISSUE THREAD

**Issue by thenkinet** [hummingbot/hummingbot-botcamp#43]
### Question

Since this breakthrough implementation of the Avellaneda-Stoikov/Fushimi strategy and more recently the VAMP script(s), I was wondering if the Hummingbot team came across other new theoritical developments on Market Making (or other topics interesting for the crypto markets). They could offer some interesting ideas for script implemntaions.

On a related matter, had the team succeeded in establishing a collaboration with Sasha Stoikov, or the CFEM (Cornell Financial Engineering Manhattan) program where Stoikov is currently an associate professor. Some students or even professors might be interested to use Hummingbot as a research tool.

Thank a lot!

**Comment by cardosofede** [comment]
@thenkinet for sure! I had a call with Stoikov some months ago and he wanted to start using Hummingbot as a research tool.
It think that @fengtality already created a private group with Cornell students.

**Comment by thenkinet** [comment]
great to hear, thanks for the feedback.
