### ISSUE TITLE
[Cohort #5] | Binance Futures Sentiment Data

### ISSUE THREAD

**Issue by thenkinet** [hummingbot/hummingbot-botcamp#45]
### Question

Binance Futures (BF) provides a unique set of sentiment data, like not many other Futures CEX does (nor traditional Futures Exchange for that matter).

Can you please explain how to pull this information from the BF connector, if possible...yet.

I am particularly interested in these 3 key metrics:
(i) OI (Open Interest)
(ii) Long/Short ratio (in position) - also available on Bitfinex
(ii) Funding rate (Real-time and history)
and to a lesser degree [Top Trader] Long/Short ratio (in account & position), Taker Buy/Sell volumes

Are the historic data (mainly for OI) available at a very low time frame, like 1min, as 5min might be a bit slow for some directional strategies.

Note: Funding rates comparison between different Futures CEX/DEX can be used for powerful "Funding Rate Arbitrage".

**Comment by cardosofede** [comment]
@thenkinet this information is not available yet in the connectors. The only thing that is available is the payments that you did of funding rate and the next estimated rate and timestamp
