### ISSUE TITLE
[Cohort #5] | Data Input & Web-hooks

### ISSUE THREAD

**Issue by thenkinet** [hummingbot/hummingbot-botcamp#46]
### Question

Can you please give us an update on how to input external data, apart from data from exchanges, in the Hummingbot scripts/strategies?

For instance, is it possible to integrate any signal (buy, sell, etc.) or information (like prices or oscillator value) from any platform providing web-hooks messages (like TradingView, but also smaller platforms like TRDR, etc.).

Same question, for "On-chain" signals from Glassnode, for instance. Can we integrate these data if they offer web-hooks; what about if they only offer an API instead. Do we need to develop a connector, like for an Exchange?

Thank you!

NB. I see there are 2 options: ConfluxBot or HelloRoger, which one you recommend and why?

**Comment by cardosofede** [comment]
@thenkinet very good question!
You will need to integrate this API to Hummingbot by creating a new DataFeed. The code is very straight forward and there is a snippet that I created for a student that wanted to use the data from an API created by him: https://www.notion.so/hummingbot-foundation/Scripts-Snippets-3b4b454c9a1049d08497beddf52c9f30?pvs=4#5106a9817afe4692bf3afad4c4b6ab22
