### ISSUE TITLE
[Cohort #5] | Use of non-standard Python Libraries

### ISSUE THREAD

**Issue by thenkinet** [hummingbot/hummingbot-botcamp#47]
### Question

There is a very complex mathematical calculation that is only available in a specific Python Library. Is it possible to import this Library for my script?

**Comment by cardosofede** [comment]
@thenkinet yes you can! but you will need to install it beforehand.

**Comment by cardosofede** [comment]
@thenkinet forgot to mention how:
There is one file inside the setup folder called environment.yml. That file contains all the dependencies that the project is using and if you want to add a new one should be here.
So then you can reinstall the conda environment with you new dependency by:
- conda deactivate
- ./uninstall
- ./install
